Repository pyt-team/challenge-icml-2024, pull requests merged in 2025-02, with the labels that each got.

#7 Vietoris-Rips Lifting (Graph to Complex)
  configs/transforms/liftings/graph2simplicial/vietoris_rips_lifting.yaml
  modules/transforms/data_transform.py
  modules/transforms/liftings/graph2simplicial/vietoris_rips_lifting.py
  test/transforms/liftings/graph2simplicial/test_vietoris_rips_lifting.py
  tutorials/graph2simplicial/clique_lifting.ipynb
  tutorials/graph2simplicial/vietorisrips_lifting.ipynb
Labels: award-category-1, award-category-3, Winner

#34 Voronoi Lifting (Pointcloud to Hypergraph)
  configs/datasets/random_pointcloud.yaml
  configs/datasets/stanford_bunny.yaml
  configs/transforms/liftings/pointcloud2hypergraph/voronoi_lifting.yaml
  modules/data/load/loaders.py
  modules/data/utils/utils.py
  modules/transforms/data_transform.py
  modules/transforms/liftings/pointcloud2hypergraph/voronoi_lifting.py
  modules/utils/utils.py
  test/transforms/liftings/pointcloud2hypergraph/test_voronoi_lifting.py
  tutorials/pointcloud2hypergraph/voronoi_lifting.ipynb
Labels: award-category-2, award-category-3, Winner

#47 Universal Strict Lifting (Hypergraph to Combinatorial)
  configs/datasets/manual_hypergraph_dataset.yaml
  configs/models/combinatorial/hmc.yaml
  configs/transforms/liftings/hypergraph2combinatorial/universal_strict_lifting.yaml
  modules/data/load/loaders.py
  modules/data/utils/utils.py
  modules/models/combinatorial/hmc.py
  modules/transforms/data_transform.py
  modules/transforms/liftings/hypergraph2combinatorial/base.py
  modules/transforms/liftings/hypergraph2combinatorial/universal_strict_lifting.py
  modules/utils/utils.py
  test/transforms/liftings/hypergraph2combinatorial/test_universal_strict_lifting.py
  tutorials/hypergraph2combinatorial/universal_strict_lifting.ipynb
Labels: award-category-2, award-category-4, Winner

#48 Mapper Lifting (Graph to Hypergraph)
  configs/transforms/liftings/graph2hypergraph/mapper_lifting.yaml
  modules/transforms/data_transform.py
  modules/transforms/liftings/graph2hypergraph/mapper_lifting.py
  test/transforms/liftings/graph2hypergraph/test_mapper_lifting.py
  tutorials/graph2hypergraph/mapper_lifting.ipynb
Labels: award-category-2, award-category-4, Winner

#49 Modularity Maximization Lifting (Graph to Hypergraph)
  configs/transforms/liftings/graph2hypergraph/modularity_maximization_lifting.yaml
  modules/transforms/data_transform.py
  modules/transforms/liftings/graph2hypergraph/modularity_maximization_lifting.py
  test/transforms/liftings/graph2hypergraph/test_modularity_maximization_lifting.py
  tutorials/graph2hypergraph/modularity_maximization_lifting.ipynb
Labels: award-category-2, award-category-3, Winner

#53 PointNet++ lifting (pointcloud to hypergraph) + new dataset
  configs/datasets/wall_shear_stress.yaml
  configs/transforms/liftings/pointcloud2hypergraph/pointnet_lifting.yaml
  modules/data/utils/utils.py
  modules/transforms/data_transform.py
  modules/transforms/liftings/pointcloud2hypergraph/pointnet_lifting.py
  test/transforms/liftings/pointcloud2hypergraph/test_pointnet.py
  tutorials/pointcloud2hypergraph/pointnet_lifting.ipynb
Labels: award-category-2, award-category-3, Winner

#58 Hypergraph Heat Kernel Lift (Hypergraph to Simplicial)
  configs/datasets/contact_primary_school.yaml
  configs/datasets/manual_hypergraph.yaml
  configs/datasets/senate_committee.yaml
  configs/transforms/liftings/hypergraph2simplicial/heat_lifting.yaml
  modules/data/load/loaders.py
  modules/data/preprocess/preprocessor.py
  modules/data/utils/utils.py
  modules/transforms/data_transform.py
  modules/transforms/feature_liftings/feature_liftings.py
  modules/transforms/liftings/hypergraph2simplicial/base.py
  modules/transforms/liftings/hypergraph2simplicial/heat_lifting.py
  pyproject.toml
  requirements.txt
  test/transforms/liftings/hypergraph2simplicial/test_heat_lifting.py
  tutorials/hypergraph2simplicial/heat_lifting.py
Labels: award-category-1, award-category-4, Winner

#50 Random Flag Couplex (Pointcloud to Simplicial)
  configs/transforms/liftings/pointcloud2simplicial/random_flag_complex_lifting.yaml
  modules/transforms/data_transform.py
  modules/transforms/liftings/pointcloud2simplicial/random_flag_complex.py
  test/transforms/liftings/pointcloud2simplicial/test_random_flag_complex_lifting.py
  tutorials/pointcloud2simplicial/random_flag_complex_lifting.ipynb
Labels: award-category-1, award-category-3, Winner

#41 Neighbourhood Complex Lifting (Graph to Simplicial)
  configs/transforms/feature_liftings/element_wise_mean.yaml
  configs/transforms/liftings/graph2simplicial/neighborhood_complex_lifting.yaml
  modules/transforms/data_transform.py
  modules/transforms/feature_liftings/feature_liftings.py
  modules/transforms/liftings/graph2simplicial/base.py
  modules/transforms/liftings/graph2simplicial/neighborhood_complex_lifting.py
  modules/transforms/liftings/lifting.py
  test/transforms/liftings/graph2simplicial/test_neighborhood_complex_lifting.py
  tutorials/graph2simplicial/neighborhood_complex_lifting.ipynb
Labels: award-category-1, award-category-4, Winner
